### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by Hanx152** [CherryCherries/nonebot-plugin-abstract#3]
05-28 10:41:31 [ERROR] nonebot | Failed to import "nonebot_plugin_abstract"
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\python\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "D:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\BOT\nb2\.\bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "D:\python\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\python\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\python\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "D:\python\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "D:\python\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "D:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\python\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\python\lib\site-packages\nonebot_plugin_abstract\__init__.py", line 7, in <module>
    from .data import text_to_emoji
  File "D:\python\lib\site-packages\nonebot_plugin_abstract\data.py", line 3, in <module>
    import jieba
  File "D:\python\lib\site-packages\jieba\__init__.py", line 14, in <module>
    from . import finalseg
  File "D:\python\lib\site-packages\jieba\finalseg\__init__.py", line 34, in <module>
    from .prob_emit import P as emit_P
ModuleNotFoundError: No module named 'jieba.finalseg.prob_emit'

**Comment by ArrebolCherries** [comment]
你安装一下jieba的python包试试，`pip install jieba`

**Comment by Hanx152** [comment]
![7 `$6`H2G7RGV7ENNO$R1F3](https://user-images.githubusercontent.com/103246532/170814177-8b6d9e72-07ab-4a84-9726-d6c667799b33.png)
![R8Q EHM$LN~K 4W8IV8@O8R](https://user-images.githubusercontent.com/103246532/170814197-078d2fc9-6f2b-45e5-8372-010cf6f4ce00.png)
还是不行

**Comment by Hanx152** [comment]
自己解决了，谢谢大佬
